import { useMemo, useState } from 'react'
import { IonApp, IonBadge, IonButton, IonCard, IonCardContent, IonContent, IonHeader, IonIcon, IonItem, IonLabel, IonList, IonNote, IonSegment, IonSegmentButton, IonText, IonTitle, IonToolbar } from '@ionic/react'
import { documentTextOutline, peopleOutline, personOutline, ticketOutline } from 'ionicons/icons'

const TYPES = { SP: { label: 'Prioritária', note: 'Atendimento preferencial', color: 'tertiary' }, SE: { label: 'Retirada de exames', note: 'Atendimento operacional especial', color: 'primary' }, SG: { label: 'Geral', note: 'Atendimento padrão', color: 'success' } }
const initial = [{ id: '261003-SP001', type: 'SP', status: 'AGUARDANDO', issuedAt: '09:05' }, { id: '261003-SE001', type: 'SE', status: 'AGUARDANDO', issuedAt: '09:12' }, { id: '261003-SG001', type: 'SG', status: 'AGUARDANDO', issuedAt: '09:20' }]
const time = () => new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })

export default function App() {
  const [tab, setTab] = useState('totem'); const [tickets, setTickets] = useState(initial); const [current, setCurrent] = useState(null); const [calls, setCalls] = useState([]); const [notice, setNotice] = useState('Selecione o tipo de atendimento para emitir sua senha.')
  const queues = useMemo(() => Object.fromEntries(Object.keys(TYPES).map((type) => [type, tickets.filter((t) => t.type === type && t.status === 'AGUARDANDO')])), [tickets])
  const replace = (ticket) => setTickets((all) => all.map((item) => item.id === ticket.id ? ticket : item))
  const issue = (type) => { const date = new Date(); const code = `${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`; const ticket = { id: `${code}-${type}${String(tickets.filter((t) => t.type === type).length + 1).padStart(3,'0')}`, type, status: 'AGUARDANDO', issuedAt: time() }; setTickets((all) => [...all, ticket]); setNotice(`Senha ${ticket.id} emitida. Aguarde a chamada no painel.`) }
  const call = () => { if (current) return; const next = queues.SP[0] || queues.SE[0] || queues.SG[0]; if (!next) return setNotice('Não há senhas aguardando atendimento.'); const ticket = { ...next, status: 'CHAMADA', desk: 'Guichê 02', firstCallAt: time() }; replace(ticket); setCurrent(ticket); setCalls((all) => [ticket, ...all]) }
  const start = () => { if (!current) return; const ticket = { ...current, status: 'EM_ATENDIMENTO', startedAt: time() }; replace(ticket); setCurrent(ticket); setCalls((all) => all.map((item) => item.id === ticket.id ? ticket : item)) }
  const recall = () => { if (!current) return; const ticket = { ...current, status: 'CHAMADA_NOVAMENTE', secondCallAt: time() }; replace(ticket); setCurrent(ticket); setCalls((all) => [ticket, ...all.filter((item) => item.id !== ticket.id)]); setNotice(`Última chamada: ${ticket.id}, Guichê 02.`) }
  const finish = () => { if (!current) return; const ticket = { ...current, status: 'ATENDIDA', finishedAt: time() }; replace(ticket); setCurrent(null); setCalls((all) => all.map((item) => item.id === ticket.id ? ticket : item)); setNotice(`${ticket.id} finalizada com sucesso.`) }
  return <IonApp><IonHeader><IonToolbar color="light"><IonTitle><b>Nassau</b> Tickets <IonNote>● Sistema ativo</IonNote></IonTitle></IonToolbar><IonToolbar color="light"><IonSegment value={tab} onIonChange={(e) => setTab(e.detail.value)} scrollable><Segment value="totem" icon={ticketOutline} label="Totem"/><Segment value="painel" icon={peopleOutline} label="Painel"/><Segment value="atender" icon={personOutline} label="Atender"/><Segment value="relatorios" icon={documentTextOutline} label="Relatórios"/></IonSegment></IonToolbar></IonHeader><IonContent className="ion-padding">{tab === 'totem' && <Totem issue={issue} notice={notice}/>} {tab === 'painel' && <Panel calls={calls}/>} {tab === 'atender' && <Attendance queues={queues} current={current} call={call} start={start} recall={recall} finish={finish} notice={notice}/>} {tab === 'relatorios' && <Reports tickets={tickets}/>}</IonContent></IonApp>
}
function Segment({ value, icon, label }) { return <IonSegmentButton value={value}><IonIcon icon={icon}/><IonLabel>{label}</IonLabel></IonSegmentButton> }
function Totem({ issue, notice }) { return <section className="screen totem"><IonText color="tertiary"><small>LABORATÓRIO DE ANÁLISES CLÍNICAS</small></IonText><h1>Olá! Como podemos ajudar?</h1><p>Escolha o tipo de atendimento e retire sua senha.</p><div className="choices">{Object.entries(TYPES).map(([type, info]) => <IonButton key={type} expand="block" fill="outline" color={info.color} onClick={() => issue(type)}><span className="code">{type}</span><span><b>{info.label}</b><small>{info.note}</small></span></IonButton>)}</div><IonCard color="tertiary"><IonCardContent>{notice}</IonCardContent></IonCard><IonNote>Atendimento de segunda a sexta, das 7h às 17h.</IonNote></section> }
function Panel({ calls }) { const recent = calls.slice(0,5); const active = recent[0]; return <section className="screen"><small className="eyebrow">PAINEL DE CHAMADAS</small><h1>Acompanhe sua chamada</h1><IonCard className="last-call" color="tertiary"><IonCardContent><small>ÚLTIMA CHAMADA</small><h2>{active?.id || '—'}</h2><b>{active ? 'Guichê 02' : 'Aguardando chamada'}</b></IonCardContent></IonCard><h2>Últimas 5 chamadas</h2><IonList inset>{recent.length ? recent.map((ticket, index) => <IonItem key={`${ticket.id}-${index}`}><IonBadge color={TYPES[ticket.type].color}>{ticket.type}</IonBadge><IonLabel>{ticket.id}<small>Guichê 02</small></IonLabel><IonNote slot="end">{ticket.secondCallAt || ticket.firstCallAt}</IonNote></IonItem>) : <IonItem><IonLabel color="medium">As chamadas aparecerão aqui.</IonLabel></IonItem>}</IonList></section> }
function Attendance({ queues, current, call, start, recall, finish, notice }) { return <section className="screen"><small className="eyebrow">ÁREA DO ATENDENTE</small><h1>Guichê 02</h1><p>Prioridade: SP → SE → SG</p><div className="queue-grid">{Object.entries(TYPES).map(([type, info]) => <IonCard key={type}><IonCardContent><IonBadge color={info.color}>{type}</IonBadge><strong>{queues[type].length}</strong><small>na fila</small></IonCardContent></IonCard>)}</div><IonCard><IonCardContent><small className="eyebrow">{current ? 'SENHA EM OPERAÇÃO' : 'PRÓXIMO ATENDIMENTO'}</small><h2>{current?.id || 'Pronto para chamar'}</h2><IonNote>{current?.status.replaceAll('_',' ') || 'A senha só é exibida após a chamada.'}</IonNote></IonCardContent></IonCard><IonButton expand="block" onClick={call} disabled={!!current}>Chamar próxima</IonButton><IonButton expand="block" fill="outline" onClick={start} disabled={!current || current.status === 'EM_ATENDIMENTO'}>Iniciar atendimento</IonButton><IonButton expand="block" fill="outline" onClick={recall} disabled={!current}>Chamar novamente</IonButton><IonButton expand="block" fill="outline" color="danger" onClick={finish} disabled={!current || current.status !== 'EM_ATENDIMENTO'}>Finalizar atendimento</IonButton><p className="notice">{notice}</p></section> }
function Reports({ tickets }) { const done = tickets.filter((t) => t.status === 'ATENDIDA').length; return <section className="screen"><small className="eyebrow">RELATÓRIO DIÁRIO</small><h1>Visão geral</h1><div className="metrics"><Metric label="Emitidas" value={tickets.length}/><Metric label="Atendidas" value={done}/><Metric label="Aguardando" value={tickets.filter((t) => t.status === 'AGUARDANDO').length}/><Metric label="Atendimento" value={`${tickets.length ? Math.round(done/tickets.length*100) : 0}%`}/></div><h2>Emissões por prioridade</h2><IonList inset>{Object.entries(TYPES).map(([type, info]) => <IonItem key={type}><IonBadge color={info.color}>{type}</IonBadge><IonLabel>{info.label}</IonLabel><b>{tickets.filter((t) => t.type === type).length}</b></IonItem>)}</IonList><h2>Auditoria recente</h2><IonList inset>{tickets.slice().reverse().map((ticket) => <IonItem key={ticket.id}><IonLabel><b>{ticket.id}</b><small>{ticket.status.replaceAll('_',' ')}</small></IonLabel><IonNote slot="end">{ticket.finishedAt || ticket.startedAt || ticket.issuedAt}</IonNote></IonItem>)}</IonList></section> }
function Metric({ label, value }) { return <IonCard><IonCardContent><strong>{value}</strong><small>{label}</small></IonCardContent></IonCard> }
